  - name: This is a play
    hosts: all
    remote_user: vagrant
    become: yes
    gather_facts: yes
 
    tasks:
      - name: install Apache
        apt: name=apache2 state=present
#        when: ansible_os_family == "Debian"
