---
# bring stack down
  - hosts: loadbalancer
    become: true
    tasks:
      - name: stop nginx
        service: 
          name: nginx
          state: stopped
 
  - hosts: webserver
    become: true
    tasks:
      - name: stop apache2
        service: 
          name: apache2
          state: stopped


# restart daatabase
  - hosts: database
    become: true
    tasks:
      - name: restart mysql
        service: 
          name: mysql
          state: restarted
          args: 
            host: "{{ ansible_eth0.ipv4.address }}"
            port: 3306
            state: started

# start stack
  - hosts: webserver
    become: true
    tasks:
      - name: start apache2
        service: 
          name: apache2
          state: started        

  - hosts: loadbalancer
    become: true
    tasks:
      - name: start nginx
        service: 
          name: nginx
          state: started

